spring.application.name=studentlist
# This is the property to specify the database and the driver here studentlist is database and mysql is driver
spring.datasource.url=jdbc:postgresql://localhost:5432/studentlist

# These properties specify the data used for authentication and authroization for the database
# no spaces anywhere(inside brackets or outside)
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#hardcoding the password fixed some things, therefore, the var env was set up wrongly

#this property is used to specify how we will handle data
spring.jpa.hibernate.ddl-auto=update

#driver class for PostgreSql
spring.datasource.driver-class-name=org.postgresql.Driver

#used to show sql whenerver any query is executed by hibernate
spring.jpa.show-sql: true
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect

debug=true